### PR TITLE
Update patch release schedule (1.15.1)

### PR DESCRIPTION
**Pull request by justaugustus**
- Reflect actual 1.12.10 release date (7/8/19)
- Remove 1.12.x as a supported version of Kubernetes
- Update patch release schedule (set 1.15.1 dates) 

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/cc @kubernetes/patch-release-team 
/assign @tpepper @feiskyer

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold

@feiskyer @tpepper -- Are we planning to cut a 1.12.10? 
The chart suggests that version is to be released in late June, but given that we just cut 1.15.0, is that still happening?

**Comment by tpepper** [comment]
Often there is one last trailing release before the oldest branch CI is turned off, just to clean out the pending queue of cherry picks.  I defer to @feiskyer on whether that's needed this time.

**Comment by justaugustus** [comment]
Thanks for the input, Tim!

**Comment by feiskyer** [comment]
I'm planning to cut the final release at the end of June. Not sure whether there's enough time to clean out the queue yet.

**Comment by justaugustus** [comment]
Sounds good. Keep us posted, @feiskyer!
I'll keep this PR on hold until we cut 1.12.10. :)

**Comment by justaugustus** [comment]
@feiskyer (Patch Release) and @listx (Build Admin) are confirmed for 1.15.1 on 7/18.
/assign @calebamiles @tpepper @listx

**Pull request merged**
