### PR TITLE
Add 1.20 release-notes-draft to release-notes directory

### PR DESCRIPTION
**Pull request by wilsonehusin**
Signed-off-by: Wilson E. Husin <whusin@vmware.com>

#### What type of PR is this:

/kind cleanup

#### What this PR does / why we need it:

Backporting #1468 as we need it for test completion (see https://github.com/kubernetes/release/pull/1922)

#### Special notes for your reviewer:

/cc @puerco @hasheddan

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@wilsonehusin can we just modify the test to run against master branch?

**Comment by wilsonehusin** [comment]
🤔 I was thinking about that too, but I worry that the behavior of the test would drift from the actual execution, since full release is taken from `release-x.y` branch, correct? or is that no longer the case because of fast-forwarding behavior that we started doing in 1.20?

**Comment by hasheddan** [comment]
@wilsonehusin the changelog command allows for execution on an arbitrary repo, so we technically are not scoped to what is available in k/k, but I understand the sentiment. Another option would be to make the location of the generated notes configurable. Right now the [sig-release repo is hard-coded](https://github.com/kubernetes/release/blob/d71805402dab160d601bdbe32c5e9178dd82d29f/pkg/changelog/changelog.go#L406), but I could see the desire to point to another location in the future, potentially even locally. In general, these tests seem more like integration / e2e tests rather than the unit tests we are using them as. I would prefer that we don't clone all of k/k for example on each run when we could just construct a mock locally. Anyway -- what do you think about making the remote location configurable and using 1.20 for now?

**Comment by wilsonehusin** [comment]
yeah I gave it more thought last night and I think we should probably just mock out the tests. I'll close this one for now.

**Pull request closed without merging**
