### PR TITLE
Update release notes draft to version v1.22.0-alpha.1

### PR DESCRIPTION
**Pull request by pmmalinov01**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.22.0-alpha.1

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

### CODE REVIEW

**Comment by wilsonehusin** [comment]
👀 did you rebuild krel? looks like it's not publishing under `release-notes/` yet

**Comment by wilsonehusin** [comment]
to clarify -- that can wait, just want to make sure if it was a bug

**Comment by pmmalinov01** [comment]
I have not rebuild krel, I started a new session yesterday(before [1922](https://github.com/kubernetes/release/pull/1922) merged) and just got time to finish it. I was going to move the drafts manually for the last time and rebuild krel.

**Review by Damans227 — APPROVED** [review]
/lgtm

**Comment by sladyn98** [comment]
Looks good

**Pull request merged**
