### PR TITLE
Add Bug Triage Tracking sheet

### PR DESCRIPTION
**Pull request by MonzElmasry**
#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:
This pr adds the tracking sheet for Bug Triage Team to release docs. 

#### Which issue(s) this PR fixes:
None

### CODE REVIEW

**Review by savitharaghunathan — APPROVED** [review]
/lgtm
/approve

**Comment by savitharaghunathan** [comment]
@MonzElmasry Can you fix the conflict when you get some time. Thanks

**Comment by annajung** [comment]
/lgtm

thank you!

**Pull request merged**
