### PR TITLE
Added incomplete draft of Bug Triage role.  Still needed: more exampl…

### PR DESCRIPTION
**Pull request by jberkus**
…e searches and reports.  Will get finished out in the 1.10 cycle.

### CODE REVIEW

**Comment by jberkus** [comment]
ooops, nobody assigned

/assign @jdumars

**Comment by jdumars** [comment]
rebase and I'll LGTM

**Comment by calebamiles** [comment]
turns out GitHub will let you rebase automagically by clicking buttons. Buttons so thus clicked.

**Comment by jdumars** [comment]
MAGIC!!

**Pull request merged**
