### PR TITLE
Add graphic about code thaw and code freeze

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:
This should visualize the differences between Code Freeze and Code Thaw
when putting them into the release cycle.
#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None

### CODE REVIEW

**Comment by LappleApple** [comment]
Love all these diagrams :)

**Comment by saschagrunert** [comment]
> Looks to be rendering a bit strangely for me. It looks like about a fourth of the image does not have background and the rest has white background. Since this will be rendered in a README not sure if it makes much of a difference though

Should be fixed now, that seems a bug in LucidChart.

**Pull request merged**
