### PR TITLE
Additional 1.12 RT members

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <foo@agst.us>

/assign @tpepper 
/hold
/sig release

### CODE REVIEW

**Comment by tpepper** [comment]
I'd like Mohammed Zeeshan Ahmed @mohammedzee1000 to affirm the shadow add, but he's not yet an org member...?

**Comment by mohammedzee1000** [comment]
+1 to adding Suraj Narwade as one of my shadows

**Comment by audrey2424** [comment]
Close this one

**Pull request merged**
