### PR TITLE
Add tombstone and retired roles section for Test Infra

### PR DESCRIPTION
**Pull request by justaugustus**
Follow-ups to #669.
ref: https://github.com/kubernetes/sig-release/pull/669#pullrequestreview-250207603, https://github.com/kubernetes/sig-release/pull/669#issuecomment-502791233

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by imkin** [comment]
This link does not work.
https://github.com/kubernetes/sig-release/blob/b39d3c228ab294b771d57fd0aea226f1fdd6d610/release-team/role-handbooks/branch-manager/README.md

**Comment by calebamiles** [comment]
I'm assuming that the `README.md` is to come later?

**Comment by justaugustus** [comment]
@imkin / @calebamiles -- order of operations problem. 
There were multiple PRs in flight changing similar content, namely #689, which moved the Branch Manager `README.md` to https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md

Once @Bubblemelon's PR lands (#666), I'll sweep the links again.

p.s. I personally don't think there's anything wrong with auto-approve. It's only on for people who are owners of the relevant sections of code. There's nothing here that can't be fixed with a follow-up PR. :)

**Comment by justaugustus** [comment]
(Usually, if it's something that requires explicit approval from someone else, you'd `/hold` it. This was not a requirement here.)

**Comment by imkin** [comment]
No tasks were moved to Bug-Triage role. The roles were only split between branch-manager and test-infra-oncall.

**Comment by justaugustus** [comment]
@imkin I think that's fine to start. If we find we need to shift tasks off to Bug Triage, we can at a future date. Will remove reference to Bug Triage in the follow up PR.

**Comment by imkin** [comment]
I think auto-approve should wait for lgtm's from assigned reviewers. If the reviewers are not "active" or "responsive" then we should unassign them. but this is beyond the scope of this PR. Thanks @justaugustus for cleaning things up.

**Comment by justaugustus** [comment]
Assigned reviewers don't encompass the entire scope of "people who are qualified to review a PR", merely a subset. 
IIRC, `required_reviewers` [example](https://github.com/kubernetes/test-infra/blob/4a79c95955a670b16d2c96d397860bf511645153/prow/OWNERS#L18) can be used for that, but I don't believe that level of granularity is required for this repo.

**Pull request merged**
