### PR TITLE
patch release schedule updates v2

### PR DESCRIPTION
**Pull request by tpepper**
Update for beginning of September as we've finished 1.16 and are operating on 1.19 maintenance.

/kind cleanup
/kind documentation
/hold

### CODE REVIEW

**Comment by tpepper** [comment]
Will rebase once https://github.com/kubernetes/sig-release/pull/1209 is merged, and remove hold once 1.16.15 has shipped on 9/2.

**Comment by tpepper** [comment]
@kubernetes/release-managers fyi

**Comment by tpepper** [comment]
Rebased.  Still holding for 1.16 to actually finish.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

are we not updating the schedule yaml file?

**Comment by tpepper** [comment]
> /lgtm
> 
> are we not updating the schedule yaml file?

So...this is an odd situation.  I'd like to commit a change like:

```
diff --git a/releases/schedule.yaml b/releases/schedule.yaml
index 68fe341..d85e141 100644
--- a/releases/schedule.yaml
+++ b/releases/schedule.yaml
@@ -1,13 +1,22 @@
 schedules:
+- release: 1.19
+  next: 1.19.1
+  cherryPickDeadline: 2020-09-04
+  targetDate: 2020-09-09
+  endOfLifeDate: 2021-09-30
+  previousPatches:
+    - release: 1.19.2
+      cherryPickDeadline: 2020-09-11
+      targetDate: 2020-09-16
+    - release: 1.19.1
+      cherryPickDeadline: 2020-09-04
+      targetDate: 2020-09-09
 - release: 1.18
   next: 1.18.9
   cherryPickDeadline: 2020-09-11
   targetDate: 2020-09-16
```

But that results in:
```
### 1.19

Next patch release is **1.19.1**

End of Life for **1.19** is **2021-09-30**

| PATCH RELEASE | CHERRY PICK DEADLINE | TARGET DATE |
|---------------|----------------------|-------------|
| 1.19.1        | 2020-09-04           | 2020-09-09  |
| 1.19.2        | 2020-09-11           | 2020-09-16  |
| 1.19.1        | 2020-09-04           | 2020-09-09  |

### 1.18
```

Which I guess is part of why https://github.com/kubernetes/sig-release/pull/1209/commits/cb4146fe57588ec3905c7663a8d59781341ce37d happened maybe?  There's a (very slow) race in how we advertise things starting and ending in the month-ish of starting a new release branch and finishing a release branch versus how the yaml generates the markdown.

I'll go ahead and commit a change to the yaml file also, but wont use the generated markdown.

**Comment by tpepper** [comment]
@cpanato what do you think?

**Comment by justaugustus** [comment]
/lgtm
/approve
/hold cancel

@tpepper @cpanato -- Would mind opening an issue for the data race?

**Comment by justaugustus** [comment]
Errrrr:
/hold since this contains the 1.19.2 date.

Tim can you split that out from the EOL?

**Comment by justaugustus** [comment]
Oops, too slow with the hold

**Comment by cpanato** [comment]
@tpepper sgtm thanks for that.
I will check the error and open an issue

**Comment by tpepper** [comment]
> Errrrr:
> /hold since this contains the 1.19.2 date.
> 
> Tim can you split that out from the EOL?

Was this referencing specifically the commit on the .yaml file?  That file's not actively used by anything just yet so I'm not too worried about it having merge or revert conflicts and needing fine grained commit content in the next week and a half.

**Pull request merged**
