### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by xiezongzhe**
kubenetes->kubernetes

### CODE REVIEW

**Comment by jdumars** [comment]
@xiezongzhe please get the CLA signed and we can proceed.

**Comment by xiezongzhe** [comment]
l have signed  it

**Comment by krzyzacy** [comment]
what's going on with other unrelated changes? :-)

**Comment by justaugustus** [comment]
@krzyzacy -- Not sure. Outside of the newline, doesn't look like there are any other changes.

**Comment by justaugustus** [comment]
That's probably it.

**Comment by jdumars** [comment]
@xiezongzhe please return the lines that should not be changed back to their original format, and I will get this merged. Thanks!

**Comment by justaugustus** [comment]
Closing this in favor of #373.
I noticed that all of the csvs I initially pulled in had CRLFs, so that PR adjusts them to LFs, as well as incorporates @xiezongzhe's typo fix.

/close

**Pull request closed without merging**
