### PR TITLE
Removing "Secondary release manager" role (dup by the Lead Shadow)

### PR DESCRIPTION
**Pull request by idvoretskyi**
Removing the "Secondary release manager" role as it's duplicated by the Release Lead Shadow.

### CODE REVIEW

**Comment by enisoc** [comment]
Can you also update the wording in the README to match?

https://github.com/kubernetes/sig-release#release-team-secondary

**Comment by idvoretskyi** [comment]
@enisoc https://github.com/kubernetes/sig-release/pull/56

**Comment by idvoretskyi** [comment]
CLA verified.

**Comment by jdumars** [comment]
Oh the irony here.

**Comment by idvoretskyi** [comment]
Closing as already fixed in https://github.com/kubernetes/sig-release/blob/master/releases/release-1.10/release_team.md

**Pull request closed without merging**
