### PR TITLE
[1.10] Release Team

### PR DESCRIPTION
**Pull request by enisoc**
This PR will be used to collect volunteers for the 1.10 [release team roles](https://github.com/kubernetes/sig-release#kubernetes-release-team-roles).

To volunteer, post a comment on this thread stating which role you're interested in, and your Kubernetes Slack handle if it's different from your GitHub handle.

### Notes

* The lead should have experience on a previous release team. However, anyone who's interested but hasn't been on a release team before is encouraged to volunteer as a shadow.
* The Patch Manager, Branch Manager, and Test Infra roles still need to be Googlers due to technical limitations in our current test/release infrastructure.

## Release Team Roles

| **Role** | **Name** (**GitHub/Slack ID**)  | **Shadow Name(s) (GitHub/Slack ID), ...** |
| ------ | ------ | ------ |
| Lead | | |
| Secondary | | |
| Features | | |
| CI Signal | | |
| Test Infra | Cole Wagner ([@cjwagner](https://github.com/cjwagner)) | Benjamin Elder ([@BenTheElder](https://github.com/bentheelder)) |
| Bug Triage | | |
| Branch Manager | | |
| Docs | | |
| Release Notes | | |
| Marketing | | |
| Patch Release Manager | | |
| Approval Notifier | k8s-ci-robot ([@k8s-ci-robot](https://github.com/k8s-ci-robot)) | |

### CODE REVIEW

**Comment by cjwagner** [comment]
I haven't had a release role before, but I'm happy to fill any test-infra role I can.  @BenTheElder can help with test-infra stuff as well.

**Comment by shyamjvs** [comment]
I'm willing to take up the PRM role.

**Comment by wjiangjay** [comment]
I'm interested with the Feature part, also not a release role before.

**Comment by idvoretskyi** [comment]
@enisoc @calebamiles any specific reason why this PR is put on hold?

IMO, it's easier to merge it as-is and let others submit their names with the following PRs.

**Comment by jdumars** [comment]
Volunteering to lead this release.

**Comment by jdumars** [comment]
Also, from the other document (deprecated), Nick Chase has volunteered for Release Notes, Jennifer Rondeau for docs, and Kaitlyn O'Connell from Cloud Foundry Foundation for marketing.

**Comment by idvoretskyi** [comment]
@jdumars can you submit a PR please?

**Comment by jdumars** [comment]
@idvoretskyi should it have all of the names so far in it?  :) Confused a little by how we're doing it this time.

**Comment by enisoc** [comment]
@idvoretskyi I initially announced (in the first post of this thread) that people should just comment here to volunteer. I figured I would take on the extra work of maintaining the running list to save applicants the hassle of creating their own PRs. It also makes it easy to see, before volunteering, what roles are and aren't filled.

@jdumars Since you've volunteered to lead 1.10, you're welcome to take over the recruitment process through whatever mechanism you prefer. However, I'm happy to keep updating this list based on comments in order to keep all the info in one place.

**Comment by jdumars** [comment]
I think we should keep it here for now.  Why upset the apple cart.  I will create a PR with everyone we have thus far, and we'll just iterate.

**Comment by abiogenesis-now** [comment]
Volunteering to shadow @Bradamant3 on the docs! (We've discussed on slack, let me know if you have any questions)

**Comment by swade1987** [comment]
Volunteering to shadow the branch manager.

**Comment by enisoc** [comment]
@swade1987 Unfortunately, the Patch Manager, Branch Manager, and Test Infra roles still need to be Googlers due to technical limitations in our current test/release infrastructure.

**Pull request merged**
