### PR TITLE
Updating the communications role handbook

### PR DESCRIPTION
**Pull request by mickeyboxell**
Updated the handbook for the Kubernetes Release Team Communications Coordinator with additional information based on my experience as the Communications Coordinator for Kubernetes 1.24.

#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:
Adds information to the release team comms handbook

### CODE REVIEW

**Comment by leonardpahlke** [comment]
Thanks @mickeyboxell ! :)  
/lgtm
/hold for @katcosgrove & @fsmunoz

**Comment by fsmunoz** [comment]
I'm happy to see several  things I have on my working copy of the 1.26 Communications Handbook review (e.g. the SIG Slack channels being used for reminders), and it clarifies and better phrases several aspects. While there are some of them that will need to change (because of e.g. using GitHub project boards), this is true for the current version as well, and I think this review is an improvement.

/lgtm

**Review by fsmunoz — APPROVED** [review]

**Comment by mickeyboxell** [comment]
> I'm happy to see several things I have on my working copy of the 1.26 Communications Handbook review (e.g. the SIG Slack channels being used for reminders), and it clarifies and better phrases several aspects. While there are some of them that will need to change (because of e.g. using GitHub project boards), this is true for the current version as well, and I think this review is an improvement.
> 
> /lgtm

I agree about adding the note about the GitHub project boards. That's a large change that should be called out in a future iteration of the docs.

**Comment by fsmunoz** [comment]
@mickeyboxell yes, since this is the first release that is using it I'm collecting things as we go and will submit a revision PR when the release is near the end - still some things changing and hindsight will help in making a core coherent, single revision.

**Pull request merged**
