### PR TITLE
Add artifact distribution policy KEP to roadmap

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:
This KEP is owned by SIG Release and should be part of our roadmap, too.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
cc @hh @ameukam

### CODE REVIEW

**Comment by saschagrunert** [comment]
Refers to https://github.com/kubernetes/enhancements/issues/3055

**Comment by ameukam** [comment]
/lgtm
/hold

If others folx want to comment.

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by justaugustus — APPROVED** [review]
/hold cancel

**Pull request merged**
