### PR TITLE
Improvements to the release_phases.md docs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:
- Fix some links and typos
- Improve a bit wording and formatting
- Clarify _Code Thaw_ in conjunction with the new schedule
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold Code Thaw was purposely excluded from the schedule
I'll look at this later.

**Comment by tpepper** [comment]
@justaugustus see recent discussion and communication, eg:

 * https://kubernetes.slack.com/archives/C2C40FMNF/p1594056738290600
 * https://groups.google.com/d/msg/kubernetes-dev/0SQSQ1Ldkr4/wqGLWfIqBQAJ

"Thaw" does still also represent a signal to folks to go forth and do dev on the main branch, and that from that point any changes for the release branch will need to be cherry picked.  This is a conceptual turning point to which it remains useful to refer by some name.  Lacking this we have a gap:

Today the [1.19 schedule](https://github.com/kubernetes/sig-release/blob/db0a550b7f2598cda86fd5a20b3a6ada45b7d0e4/releases/release-1.19/README.md) indicates a start of code freeze, but there's no clear point noted for the symmetric action ending that period.

**Pull request merged**
