### PR TITLE
Add initial information for Release Managers roles

### PR DESCRIPTION
**Pull request by justaugustus**
As mentioned on a few SIG Release, 1.15 Release Team meetings, and the 1.15 Retro, Branch Managers are moving out of the Release Team and under the Release Engineering subproject for Kubernetes 1.16.
The Patch Release Team has already made that move, so it's a good time to update the docs around some of this.

This PR is an initial documentation of the intent for the various Release Manager roles, as well as contact information for each.

We're intending to iterate over this documentation in the 1.16 release cycle, so consider this just a first step in getting things more up-to-date.

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @tpepper @calebamiles 

For PSC visibility:
/cc @philips @cjcullen @tallclair @liggitt @joelsmith @micahhausler @jonpulsifer 

For GH Admin visibility (ref: https://github.com/kubernetes/org/pull/927#issuecomment-503698072):
/cc @kubernetes/owners 

A more formal notification will go out to k-dev once this PR lands.

**Comment by cblecker** [comment]
No objections from me.

**Pull request merged**
