### PR TITLE
Request that we publish Debs and RPMs for beta and release candidates

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I3eac113f7ad23b0e813d9fb59fbd9241887da9ec

### CODE REVIEW

**Comment by neolit123** [comment]
+1

**Comment by calebamiles** [comment]
/hold

@dims I don't believe this is actionable at this point. In my opinion we need to

1. blockade all deb/rpm specifications which live here in favor of those which live in [kubernetes/build][] (this also solves a large part of the "release tooling should be versioned" problem as the specs will be bundled with the version of Kubernetes that they apply to)
1. migrate deb/rpm hosting to a community maintained project (rather than being hosted on Google repositories)
1. move deb/rpm generation into `anago` so that the process actually becomes automated and stops lagging image publishing
1. profit

Rather than creating [issues][] in a poorly trafficed repository this really should be worked as part of a KEP given the impact. 

**cc: @jagosan**

[kubernetes/build]: https://github.com/kubernetes/kubernetes/tree/master/build
[issues]: https://github.com/kubernetes/release/issues/631

**Comment by dims** [comment]
@calebamiles ack on all the points :) @spiffxp told me to!

**Comment by hoegaarden** [comment]
In addidtion to Caleb's point:

> 2. migrate deb/rpm hosting to a community maintained project (rather than being hosted on Google repositories)

If we publish RC debs, we should publish them as a separate distribution (compare: debian's `stable`, `testing`, `unstable`, `experimental`). Then users can opt-in to the RC releases (by adding this new distribution and setup pinning or explicitly install from that distribution via `apt-get install -t ...` or such) and won't be surprised by an RC release coming in all of a sudden.
Same should be done for rpms.

**Pull request closed without merging**
