### PR TITLE
First release_notes_draft.md of k/k 1.18.0-alpha.1

### PR DESCRIPTION
**Pull request by evillgenius75**
Release Notes draft for k/k v1.18.0-alpha.1
```
release-notes \                                                         
--branch=master \
--github-token=$GIT_TOKEN \
--repo-path  /tmp/k8s \
--release-version 1.18.0 \
--format markdown \
--output releases/release-1.18/release-notes-draft.md \
--start-sha 663a303b6fcec07dfd05657583df337aba329d13 \ #sha of last commit of k/k tag v1.17.0-rc.1
--end-sha ac4079a5cc22ced66c868f6fd26f8e2497765e51 \ #sha of last commit of k/k tag v1.18.0-alpha.1
```

### CODE REVIEW

**Comment by evillgenius75** [comment]
/assign @daminisatya

@justaugustus @saschagrunert

**Comment by saschagrunert** [comment]
Thanks!

I contacted the maintainers of https://github.com/kubernetes/kubernetes/pull/85621 and https://github.com/kubernetes/kubernetes/pull/74525 to ask for an adaption of their PR descriptions. 

In any case, I’m not sure if we should use the RC as last Tag and would prefer to use the final tag, because issues like https://github.com/kubernetes/kubernetes/pull/85810 should be probably not part of it. WDYT?

**Comment by evillgenius75** [comment]
@saschagrunert I agree as the start-sha should be the latest commit sha of 1.17.0 which was the final release I just want to make sure we don't lose pertinent PRs.

**Comment by saschagrunert** [comment]
> @saschagrunert I agree as the start-sha should be the latest commit sha of 1.17.0 which was the final release I just want to make sure we don't lose pertinent PRs.

Do you mind another re-generation? 😊

**Comment by evillgenius75** [comment]
@saschagrunert when I rerun there are dramatically less commits from 749 to 349, so seems a little drastic. U used the last commit sha of v1.17.0 tag for the start-sha and the last commit sha of the v1.18.0-alpha.1 tag.
Also I am getting a new error I didn't see on last release cycle. its seems github is seeing multiple calls to the API with some kind of abuse detection and is backing off. Not sure if we are losing fidelity because the release-notes tool is not able to catch this?
```
INFO starting to process commit 293 of 349 (83.95%): 7a9788be8cc0a45e0f8d1a238fb4320b83450240 
INFO starting to process commit 294 of 349 (84.24%): 49e4bd137bd3c69d0cf81c0c4ab51ab0d5674f87 
INFO Hit the abuse rate limit on try 1, sleeping for 1m0s  err="GET https://api.github.com/repos/kubernetes/kubernetes/pulls/86099: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
INFO Hit the abuse rate limit on try 1, sleeping for 1m0s  err="GET https://api.github.com/repos/kubernetes/kubernetes/commits/49e4bd137bd3c69d0cf81c0c4ab51ab0d5674f87/pulls?page=1&per_page=100&state=closed: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
INFO Hit the abuse rate limit on try 1, sleeping for 1m0s  err="GET https://api.github.com/repos/kubernetes/kubernetes/pulls/86096: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
INFO Hit the abuse rate limit on try 1, sleeping for 1m0s  err="GET https://api.github.com/repos/kubernetes/kubernetes/pulls/85838: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
INFO Hit the abuse rate limit on try 1, sleeping for 1m0s  err="GET https://api.github.com/repos/kubernetes/kubernetes/pulls/75583: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
INFO Hit the abuse rate limit on try 1, sleeping for 1m0s  err="GET https://api.github.com/repos/kubernetes/kubernetes/pulls/85452: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
INFO starting to process commit 295 of 349 (84.53%): 8647e75cec684fce64280b6079ef174643548c53 
INFO starting to process commit 296 of 349 (84.81%): 009c731a8800940879290f8684ae2f5a97bb01f6 
INFO starting to process commit 297 of 349 (85.10%): c051fc2057ac0f1daf126e381bda5f61961e0080 
INFO starting to process commit 298 of 349 (85.39%): c7a65ca0c352d58d94327ed80f35757bef3d6792 
INFO starting to process commit 299 of 349 (85.67%): bbd48e99b2c19d999dfa25320f055a20deabbc38 
```

I can still merge the changes if you want with the new run.

**Comment by saschagrunert** [comment]
Hm, from my logical understanding it should be fine to go from v1.17.0 to the latest master, but I might miss something...I’ll give it a try tomorrow. :)

The rate limiting warning got introduced due to latest changes in the release notes tool. It should be now much faster, but we have to wait for GitHub to overcome the API rate limiting. :)

**Comment by evillgenius75** [comment]
Got it! It was much faster for sure. I will hold off on the merge until you check your run, but I have an updated .md file with the new run when needed.

**Comment by saschagrunert** [comment]
I think we have a more general issue with the release notes generation and the retrieval of the start commit:
https://github.com/kubernetes/release/blob/master/pkg/notes/notes.go#L382

We basically retrieve the start commit by choosing one from a different branch from the master (like v1.17.0) and then use that commit date to point to the master branch. This only works when we're using the same commit which got introduced by [Code Freeze](https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md#code-freeze), to not miss any merges on the master afterwards. This means we're correct in using `v1.17.0-rc.1` on release notes generation with the current tooling.

So something like this should work fine:
```
> go run cmd/release-notes/main.go --github-token $TOKEN --start-rev v1.17.0-rc.1 --end-rev master
```

Seems quite complicated, since we're mixing up our processes with the technical solution behind it. It would be easier to use the merge-base of the `release-1.17` branch as start rev. I'll follow up on that topic in a PR.

**Comment by justaugustus** [comment]
@evillgenius75 @saschagrunert -- Where did we land with this?

Do we want to handle the general issue separately, so as to not block the drafts?
If so...
/lgtm
/approve

/hold (feel free to lift if y'all determine this is good to go)

**Comment by saschagrunert** [comment]
Let's take it in, that's totally fine for now :+1: 
/unhold

**Pull request merged**
