### PR TITLE
Updated 1.18 release team lead shadows

### PR DESCRIPTION
**Pull request by alejandrox1**
Signed-off-by: alejandrox1 <alarcj137@gmail.com>

### CODE REVIEW

**Comment by alejandrox1** [comment]
/hold
/assign @onlydole :tada: 
Thank you!

**Comment by smourapina** [comment]
Congrats and welcome @onlydole ! 🎉

**Comment by markyjackson-taulia** [comment]
Congrats @onlydole !!!!!

**Comment by onlydole** [comment]
/lgtm 

I’m stoked! Thank you again for the opportunity!

**Comment by alejandrox1** [comment]
Let's make it official
/hold cancel

**Pull request merged**
