### PR TITLE
Release Notes draft for k/k v1.19.0-alpha.2

### PR DESCRIPTION
**Pull request by puerco**
> /kind documentation

#### What this PR does / why we need it:
First attempt at generating the release notes draft for version 1.19. 

#### Special notes for your reviewer:

We ran the krel release notes subcommand with the following options:
```
krel release-notes \
   --create-website-pr \
   --website-org=puerco \
   --tag v1.19.0-alpha.2  
```
/cc @reylejano-rxm @AGMETEOR  @wilsonehusin @JamesLaverack

### CODE REVIEW

**Comment by puerco** [comment]
Im holding this one because we have doubts on the start tag
/hold

**Comment by puerco** [comment]
Releasing hold as we have confirmed the start tags with @saschagrunert during the 1.19 release team call.
/hold cancel
/assign @onlydole

**Comment by onlydole** [comment]
Thank you, team! This looks good to me.

/approve

**Pull request merged**
