### PR TITLE
Update release-notes-draft.md

### PR DESCRIPTION
**Pull request by wangxy518**
update an url

### CODE REVIEW

**Review by soniasingla — APPROVED** [review]
/approve

Thanks for the PR! 🎉

**Comment by jeremyrickard** [comment]
Hey @wangxy518, thanks for the PR to fix that link. Unfortunately, this PR would only update the draft release notes and not the actual 1.7 release notes. The actual release notes won't be regenerated off of this, so this modification isn't really appropriate to merge here.

**Comment by puerco** [comment]
Closing this for the reasons noted by Jeremy above.
/close

**Pull request closed without merging**
