### PR TITLE
updated release notes draft Aug 12, 2019

### PR DESCRIPTION
**Pull request by cartyc**
Weekly release note draft update.

release-notes -start-sha 02dc3d713dd7f945a8b6f7ef3e008f3d29c2d549 \
-end-sha 0610bf0c7ed73a8e8204cb870e20c724b24c0600

### CODE REVIEW

**Comment by saschagrunert** [comment]
The changes LGTM but did you start from the most recent version? It seems that we have a merge conflict :)

**Comment by cartyc** [comment]
I'll take a look later today. Thought I synced things last night, might have missed something. That's what I get for doing a PR before breakfast :(

**Comment by saschagrunert** [comment]
LGTM

**Pull request merged**
