### PR TITLE
cleanup missing hyperlink

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this:
/kind cleanup

#### Which issue(s) this PR fixes:

None

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/hold
if @wilsonehusin wants to merge https://github.com/kubernetes/sig-release/pull/1371 first

**Comment by wilsonehusin** [comment]
I think there should be no conflicts if #1371 goes in first so I'm going to vote that we merge this after #1371

**Review by hasheddan — APPROVED** [review]
@249043822 looks like a small rebase is needed here then should be good to merge :)

/lgtm

**Comment by 249043822** [comment]
@hasheddan I have rebased, thanks

**Review by soniasingla — APPROVED** [review]
/lgtm

**Comment by wilsonehusin** [comment]
thanks for the fix!

/hold cancel

**Pull request merged**
