### PR TITLE
Add a date for docs PR placeholder PRs

### PR DESCRIPTION
**Pull request by zacharysarah**
This PR:
- Adds a date (Friday, May 25) by which placeholders PRs must be open for docs

### CODE REVIEW

**Comment by calebamiles** [comment]
deferring to @jberkus to merge

**Comment by zacharysarah** [comment]
@jberkus Bump for review.

**Comment by jberkus** [comment]
OOps, because of clobbering your branch I've replaced this with PR #152.  Sorry.

**Comment by jberkus** [comment]
Closing this because #152 merged with that deadline.

**Pull request closed without merging**
