### PR TITLE
Added exceptions.yaml file for v1.31

### PR DESCRIPTION
**Pull request by sreeram-venkitesh**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it: 

Adds the exceptions.yaml file for the v1.31 release.

#### Special notes for your reviewer:
CC: @Priyankasaggu11929 @neoaggelos 

/hold

### CODE REVIEW

**Comment by sreeram-venkitesh** [comment]
I will keep adding all the exceptions here and we can merge after all the exceptions have come through. Pushed just the base file for now. Will add the current exceptions in some time.

**Comment by Priyankasaggu11929** [comment]
/lgtm
/approve

/hold

Thank you @sreeram-venkitesh!

**Comment by neoaggelos** [comment]
ty @sreeram-venkitesh!

/lgtm
/hold cancel

**Pull request merged**
