### PR TITLE
Convert HTML to Markdown in role-handbooks

### PR DESCRIPTION
**Pull request by justaugustus**
...I'm honestly not sure if this is better or worse than it was before.

/assign @tpepper @AishSundar 
/sig release
/shrug

Signed-off-by: Stephen Augustus <foo@agst.us>

### CODE REVIEW

**Comment by AishSundar** [comment]
I dont see much of a difference either (infact I liked the prev one better on the UI :)) But I agree markdown is becoming the standard across, so this change is good. LGTM from me and I will let other reviewers or you remove the hold when appropriate.

/hold
/lgtm

**Comment by wadadli** [comment]
Markdown is certainly much more maintainable than HTML.
/lgtm

**Comment by tao12345666333** [comment]
Markdown is certainly much more maintainable than HTML. +1 
(Keep it simple)

**Comment by tpepper** [comment]
I dislike making this a markdown table. Would probably go for markdown if the elements used were sections and bullets and paragraphs and sentences. 

Imho good markdown is readable both raw and rendered and raw text is a valid use case when it comes to things like grep, diff, patch, git {log, diff, blame, ...} and such.

**Comment by tao12345666333** [comment]
@tpepper  Do you mean we don't use the full Markdown syntax? For example: except table syntax.

**Comment by tpepper** [comment]
A giant line of text that still has embedded html like ```
| 1 | - Start the release cycle <br/>- Ensure you are joined to the following Google Groups: [kubernetes-milestone-burndown](https://groups.google.com/forum/#!forum/kubernetes-milestone-burndown), [kubernetes-sig-release](https://groups.google.com/forum/#!forum/kubernetes-sig-release), [kubernetes-sig-leads](https://groups.google.com/forum/#!forum/kubernetes-sig-leads), [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) <br/>- Ensure the release team is fully filled, with members subscribed to the kubernetes-milestone-burndown@googlegroups.com group. <br/>- Create and finalize the release schedule, blocking test gates, and role assignments as a pull request in: kubernetes/sig-release/releases/release-x.y/README.md <br/>- Ensure that relevant feedback from the prior retrospective is incorporated into the process <br/>- Send an update to kubernetes-dev and kubernetes-sig-leads mailing list to announce the start of the release cycle, including any notable changes in the release process, key dates, and links to important documents <br/>- Create the retrospective document and corresponding bit.ly link <br/>- Begin meeting with SIGs to introduce yourself <br/>- Begin paying attention to [CI signal](https://git.k8s.io/sig-release/release-team/role-handbooks/ci-signal/README.md), as it may begin degrading soon after the prior release is cut and any slips must be caught and rectified promptly. <br/>- Request review of this document by the release lead shadow. The shadow should also take all actions in this document around joining groups and requesting access permissions. <br/>- Update the blockade config in \[prow/plugins.yaml\](https://git.k8s.io/test-infra/prow/plugins.yaml) to prevent changes to all but the three most recent release folders. |``` is quite awkward versus say fully committing to markdown and using the main elements markdown gives us, ie: sections and bullet lists:

```
# Week 1
 * do something
 * do something else

# Week 2
 * do more stuff
```

I suspect table gives no value here, whether markdown or html.  Both obfuscate the readability and complicate the maintainability of the raw underlying text.

**Comment by justaugustus** [comment]
@tpepper -- completely agree! To my note in the PR:
```
...I'm honestly not sure if this is better or worse than it was before.
```

I just kind of put this up so we could kick around the ideas.
I can convert to markdown only timeline, if you'd like. Just let me know! :)

**Comment by justaugustus** [comment]
@AishSundar @tpepper -- switched this to all markdown, without tables.
I'll leave you to re-`/lgtm` and pull the hold when ready.

**Pull request merged**
