### PR TITLE
Fix Release Team Selection Link

### PR DESCRIPTION
**Pull request by jasonbraganza**
#### What type of PR is this:
/kind cleanup

#### What this PR does / why we need it:
The PR fixes broken link to [release team selection](https://github.com/kubernetes/sig-release/blob/master/release-team/release-team-selection.md ) document, in the Enhancements Role handbook.

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
Thanks for the fix, @jasonbraganza.

/lgtm

**Comment by Priyankasaggu11929** [comment]
/assign @salaxander

@salaxander, this is a small fix in the enhancements role-handbook. Could you please take a look for approval? Thank you!

**Review by saschagrunert — APPROVED** [review]

**Comment by jasonbraganza** [comment]
Oh hurrah! my first PR to a major open source project, that kickstarted my devops journey is merged :) Thank you @Priyankasaggu11929 and @saschagrunert!

**Pull request merged**
