### PR TITLE
Add role leads to 1.23 release team

### PR DESCRIPTION
**Pull request by reylejano**
#### What type of PR is this:

/kind documentation
/area release-team
/priority important-soon
/milestone v1.23
/sig release

#### What this PR does / why we need it:

This PR adds the leads to the 1.23 Release Team file. 

#### Which issue(s) this PR fixes:
Ref: #1623

#### Special notes for your reviewer:
None

/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco @hasheddan
/cc @salaxander @encodeflush @voigt @jlbutler @cici37 @karenhchu

### CODE REVIEW

**Comment by puerco** [comment]
Awesome team :sunglasses: 
/lgtm
/approve

**Review by justaugustus — APPROVED** [review]
Congrats and thank you to the new Lead team!!! 💕

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
> /hold for review from others

I think this has been done
/unhold

**Pull request merged**
