### PR TITLE
SIG-Release leads updated

### PR DESCRIPTION
**Pull request by idvoretskyi**
cc @jdumars @calebamiles

### CODE REVIEW

**Comment by spiffxp** [comment]
Is there a corresponding change for kubernetes/community sigs.yaml et al?

**Comment by jdumars** [comment]
There should be an update to the yaml file, yes.

**Comment by idvoretskyi** [comment]
@spiffxp @jdumars just did it https://github.com/kubernetes/community/pull/1651

**Comment by idvoretskyi** [comment]
@spiffxp @jdumars you may proceed with this now.

**Pull request merged**
