### PR TITLE
Add basic release engineering description

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Target is to get a better onboarding experience to the release engineering sub-project by documenting the overall process from a high level perspective.

#### Which issue(s) this PR fixes:

Refers to https://github.com/kubernetes/sig-release/pull/1086

#### Special notes for your reviewer:

The level of detail is completely open and I will add a textual description if we agreed on the contents of the graphic.

### CODE REVIEW

**Comment by saschagrunert** [comment]
I see room for more details in the graphic for the topics:
- The patch release cherry-pick triage process
- The tooling side (not sure if that makes sense)

WDYT?

**Comment by onlydole** [comment]
I'm a fan, @saschagrunert! 
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by onlydole** [comment]
We have consensus! 
/approve

**Review by justaugustus — CHANGES_REQUESTED** [review]
/hold this document is inaccurate. More so now that https://github.com/kubernetes/sig-release/pull/1106 has merged.

See https://github.com/kubernetes/sig-release/blob/master/release-managers.md.

**Comment by justaugustus** [comment]
I'm working on a de-dupe of the handbooks.
Please hold for that before making further updates.

**Comment by saschagrunert** [comment]
@xmudrii do you think we still need this as part of the docs improvements?

**Comment by xmudrii** [comment]
@saschagrunert I think the diagram would be a very nice addition to the future handbooks, so we should update it and eventually add some additional information (or create another diagram for that).

**Comment by LappleApple** [comment]
What updates to the diagram are necessary?

**Comment by xmudrii** [comment]
@LappleApple We have changed the team organization and tooling a little bit since the diagram was created. Concretely:

- Branch Management and Patch Release Team are a single, Release Managers, team
- `krel gcbmgr` is now `krel stage`/`krel release`
- anago is not a thing anymore (:tada:)

Eventually, we could recap some other parts of the workflow, such as the image promotion.

**Comment by LappleApple** [comment]
What do you think about making these updates, shipping the diagram, then we make a new GH issue when the other future changes are ready to be integrated?

**Comment by xmudrii** [comment]
@LappleApple Sounds good to me! I'll need some help from @saschagrunert since I don't really know how that diagram was created and how to edit it.

**Comment by saschagrunert** [comment]
/close

@xmudrii let's follow up on that if you find some time next week :)

**Pull request closed without merging**
