### PR TITLE
Remove code slush

### PR DESCRIPTION
**Pull request by spiffxp**
We decided a clear warning to brace for code freeze was sufficient,
and a whole extra delineated phase wasn't worth the effort. We'll
still remind folks not to do mean things like land massive changes
or refactors N days before code freeze.

ref: https://github.com/kubernetes/sig-release/issues/269

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
for comment (also, ref: https://github.com/kubernetes/community/pull/3090)

**Comment by spiffxp** [comment]
I vastly underestimated how many times the word "slush" is mentioned in playbooks.  The following playbooks need an update:
- test-infra
- bug-triage
- release-notes
- branch-manager
- release-team-lead
- ci-signal
- enhancements

I would rather hold this to take an initial pass

**Comment by tpepper** [comment]
I'm also in favor of this, but definitely would prefer removal across the board so will await the amended commit / PR.

**Pull request merged**
