### PR TITLE
Cleanup the CI Signal handbook

### PR DESCRIPTION
**Pull request by mehabhalodiya**
#### What type of PR is this:
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
In Bug Triage and CI Signal Merge Discussion meeting (which happened on 14th June 2023), we agreed to clean up the CI Signal handbook more.

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
We as a team are open to having your feedback/suggestions for addition or removal of the information present in the current CI Signal handbook. Feel free to comment or head over to the `sig-release` channel for any kind of discussion.

Mentioning you people @lauralorenz @helayoty @gracenng @leonardpahlke so that you can track it on the basis of the decision taken.

Thank you.

### CODE REVIEW

**Comment by gracenng** [comment]
Are there more changes to docs beside the one in this PR?
@Vyom-Yadav

**Comment by mehabhalodiya** [comment]
@leonardpahlke @gracenng I am done from my side. Looking forward to the suggestions, if any 🙂 
Thank you!

**Comment by Vyom-Yadav** [comment]
cc @kubernetes/ci-signal 

> Are there more changes to docs beside the one in this PR? @Vyom-Yadav

@gracenng Here is my take on cleaning the handbook https://github.com/kubernetes/sig-release/pull/2276.

**Comment by gracenng** [comment]
Sorry for the delay, just had a chance to look everything over. Looks great!

/lgtm
/approve

**Pull request merged**
