### PR TITLE
Release Notes draft for k/k v1.18.0-beta.1

### PR DESCRIPTION
**Pull request by reylejano-rxm**
What type of PR is this?
/kind documentation

What this PR does / why we need it:
Generated draft of release notes with krel for k/k v.18.0-beta.1
Command used:
krel release-notes --create-draft-pr --draft-org=reylejano-rxm --tag v1.18.0-beta.1

This is the second version of the release notes draft generated with krel.
The commit was amended with my personal info with
git commit --amend --author="Rey Lejano rey.lejano@rx-m.com" --signoff

Which issue(s) this PR fixes:

Special notes for your reviewer:

cc/ @saschagrunert @evillgenius75 @puerco @JamesLaverack

### CODE REVIEW

**Comment by puerco** [comment]
All right :tada:  !

**Comment by saschagrunert** [comment]
I think I don’t have enough power for this, but
/approve

**Comment by puerco** [comment]
Thanks to all !!

**Pull request merged**
