### PR TITLE
Add exception.yaml for 1.21

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:
Add a list of exceptions for 1.21

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
cc @palnabarun @bai @savitharaghunathan @kikisdeliveryservice

### CODE REVIEW

**Comment by annajung** [comment]
Had a duplicate that I removed and fixed the duplicate link as well, @palnabarun take another look when you can. thanks!

**Comment by palnabarun** [comment]
/lgtm

missed that duplicate the first time

**Comment by kikisdeliveryservice** [comment]
thanks anna!
/lgtm

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Pull request merged**
