### PR TITLE
Remove extra CNCF content from the blog template

### LINKED ISSUE #2128: Release Blog should not include CNCF content
SIG-Release:

The current release blog template, and thus the actual release blogs from the last 3 releases, includes two sections of CNCF-generated content that are irrelevant to the release.  These are "User Highlights" and "Ecosystem Updates".

These should be removed from the template, and maybe from the 1.26 blog as well depending on how long it takes to approve this.

Reasons:

- None of the items in these sections have anything whatsoever to do with the release, which is confusing to readers.
- CNCF has their own blog where they can publish such items.
- The randomness of selection results in these sections de-facto promoting various non-Kubernetes projects and private companies
- The release blog post is already really long, and we should be making it shorter, not padding it with unrelated content

If I get some general +1s here, I'll write a PR against the blog template.  Thanks!

Attn: @fsmunoz

### PR DESCRIPTION
**Pull request by jberkus**
Per discussion.

Fixes #2128 

Attn @fsmunoz @leonardpahlke 

/kind cleanup

### CODE REVIEW

**Comment by sftim** [comment]
Should we let the CNCF marketing folks know that we're making this change?

**Review by leonardpahlke — COMMENTED** [review]
/lgtm

**Comment by leonardpahlke** [comment]
> Should we let the CNCF marketing folks know that we're making this change?

FYI @onlydole @nate-double-u 

(AFAIK the CNCF folks are not involved in the process of writing these sections and I'm not sure they are actually aware of it. :D)

**Review by saschagrunert — APPROVED** [review]
/hold

Feel free to unhold if appropriate.

**Review by fsmunoz — APPROVED** [review]
I don't have a problem with removing the content, especially the "User Stories" feel a bit our of place in a Kubernetes release article.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by jberkus** [comment]
Is there any reason for this still to be on hold?

**Comment by onlydole** [comment]
> (AFAIK the CNCF folks are not involved in the process of writing these sections and I'm not sure they are actually aware of it.) 

Thank you for the call-out, @sftim and @leonardpahlke! This is good to remove and I believe it's a holdover from the early days of Kubernetes releases. 

+1 to removing the hold and keeping the blog content focused on the release for future editions.

**Comment by saschagrunert** [comment]
/unhold

Thank you for the clarifications folks!

**Pull request merged**
