### PR TITLE
Add 1.20 mascot

### PR DESCRIPTION
**Pull request by jeremyrickard**
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>

#### What type of PR is this:
/kind documentation
/area release-team
/priority important-soon

#### What this PR does / why we need it:

This PR adds Humphrey, the 1.20 Release mascot to the README.

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Yay! 🙌🥳

/lgtm
/hold

Feel free to lift if you’re ready to merge.

**Review by hasheddan — APPROVED** [review]
/lgtm
:tada:

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm 

/meow

**Pull request merged**
