### PR TITLE
Add 1.11 release managers

### PR DESCRIPTION
**Pull request by nikhita**
Updates the release managers doc.

/cc jberkus foxish

### CODE REVIEW

**Comment by tpepper** [comment]
If you make this "update release managers" instead of "add 1.11...", can just jump us up to being ready for the next 3+ months too:

```
+ | 1.12 minor (up to 1.12.0) | Tim Pepper ([@tpepper](https://github.com/tpepper)) | - | - | - |
+ | 1.12 patch (post 1.12.0) | Pengfei Ni ([@feisky](https://github.com/feiskyer)) | - | - | - |
```

**Comment by jberkus** [comment]
/approve

Thanks, didn't even notice that doc.

**Pull request merged**
