### PR TITLE
Update branch manager handbook

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this:
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
Update branch manager handbook

### CODE REVIEW

**Review by puerco — CHANGES_REQUESTED** [review]
Thanks for updating this @cici37 !
Can you also edit the section "Branch Fast Forward" to explain that we run the branch fast forward automatically to even the branches? 

As @saschagrunert suggested in Slack, please also add a link to the FF prow job:

https://testgrid.k8s.io/sig-release-releng-blocking#git-repo-kubernetes-fast-forward

**Comment by cici37** [comment]
> un the branch fast forward automatically to even the branches

Thanks for the reminder. I have updated the branch faster forward section to match what we have now. Please take a look when have time^^

**Review by cpanato — APPROVED** [review]
/lgtm
/hold for @puerco

**Review by saschagrunert — APPROVED** [review]

**Comment by cici37** [comment]
Hi @puerco , politely ping to see if it is ok to merge this pr :)

**Review by cpanato — APPROVED** [review]
will unhold

if there is any feedback from @puerco we can do in a follow up
/unhold

**Pull request merged**
