### PR TITLE
Add context for exception list.

### PR DESCRIPTION
**Pull request by yuwenma**

### CODE REVIEW

**Comment by justaugustus** [comment]
@yuwenma -- could you also added a link to the KEP, so people have more context when they visit this page?

**Comment by yuwenma** [comment]
> @yuwenma -- could you also add a link to the KEP, so people have more context when they visit this page?

oh, right! Thanks for the reminder. Done

**Comment by justaugustus** [comment]
Thanks Yuwen!
/lgtm
/approve

**Pull request merged**
