### PR TITLE
Docs role handbook improvements

### LINKED ISSUE #1207: Improve docs role handbook
### Elaborate on the following release day tasks

- [x] Clarify on the permissions needed to add `tide/merge-blocker` label

- [x] Permissions required to cut a release. Request for temporary write access.

### Overall improvements:

- [x] ~~How to request access to view Netlify builds~~ - We will circle back later if this access is required

- [x] ~~Netlify access cleanup post release~~ -We will circle back later on this if Netlify access is granted

- [x] Setting up a URL for dev-[future-release] branch - Done (Duplicate of existing doc)

- [x] Configure release-[current-version] URL in Netlify after cutting release-[current-version] branch

- [x] Clarify on the embargo process. 

- [x] Frequent branch syncs (2/week and 3/week closer to release) 

- [x] Report the health of `dev-[future-release]` branch weekly (in #sig-docs & RT meetings)

- [x] Templates for deadline communication

- [x] Add shadows to milestone maintainers & cleanup 

- [x] ~~Define shadow roles & responsibilities~~ - Going to be a part of RT prioritization tasks

### Retro AI:

1.19:

- [x] ~~Leverage `Implemented` field from enhancements tracking sheet to determine if the corresponding docs PR can be merged/not~~ - Going to be an issue on its own as it is a little complicated

1.17:

- [x] Look into improving the current process of tracking enhancement docs with help from the enhancement team. The goal is to reduce continuous pinging noise for the enhancement and to make sure enhancement owners are aware of the docs requirement earlier in the process (Based on discussion with Enhancement lead and 1.17 retro item https://kubernetes.slack.com/archives/C2C40FMNF/p1600864910029100)

- [x] Add general obligations/expectation for a lead in the docs role handbook

cc: @jimangel  

/assign

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Addresses few tasks from #1207

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
/kind feature-
//kind documentation

**Comment by jimangel** [comment]
@savitharaghunathan feel free to ping me on slack when this is ready for review, so far it LGTM. Also, we can always merge and iterate after if you get close to completing #1207. Thanks!

**Comment by savitharaghunathan** [comment]
Thanks,Jim. I will 😊 I was waiting for sftim’s PR to be merged and it got
merged today. I will try to wrap this up tomorrow or Monday at the
earliest. Got few more stuffs to add once I rebase and pull in Tim’s
changes.

**Comment by savitharaghunathan** [comment]
@jimangel 👋 This is ready for review. I still have tasks left to clarify on the embargo process and Netlify access, which I think could go in the next PR. Thanks in advance for reviewing :)

**Pull request merged**
