### PR TITLE
Update release notes draft to version v1.22.0-beta.0

### PR DESCRIPTION
**Pull request by simcard0000**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.22.0-beta.0

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

### CODE REVIEW

**Comment by simcard0000** [comment]
Right now this is an initial PR, no edits have been made yet.

**Comment by pmmalinov01** [comment]
@simcard0000 Thanks for doing this. Unfortunately, this is not the correct flow due to the fact we review and update map files that you generated in the `--fix` workflow. I am unsure if the way you want to go can produce not error-prone results (miss a note or not update it correctly). Would prefer if you redo the this PR and review the notes one by one and create a new PR. 
Make sure to clear your fork of sig-release from the branch created by krel. 
/close

**Pull request closed without merging**
