### PR TITLE
Fixed links in ci signal handbook

### PR DESCRIPTION
**Pull request by alejandrox1**
Signed-off-by: alejandrox1 <alarcj137@gmail.com>

### CODE REVIEW

**Comment by scottilee** [comment]
@alejandrox1 This looks good to me but there are a couple more links on the bottom of the page that also need fixing. They can be a separate pull request but FYI here are where I found additional broken links.

Screen Shot 2019-07-15 at 3 39 30 PM
Screen Shot 2019-07-15 at 3 41 48 PM
Screen Shot 2019-07-15 at 3 43 03 PM
Screen Shot 2019-07-15 at 3 43 26 PM

**Comment by alejandrox1** [comment]
Fixed OR based on your comments @scottilee 
ptal

**Comment by scottilee** [comment]
/lgtm

Although you'll probably need someone else to approve.

**Pull request merged**
