### PR TITLE
v1.11 release team - add colemickens as shadow bug triage

### PR DESCRIPTION
**Pull request by colemickens**
Hello. I'd like to volunteer to do `Bug Triage` for the v1.11 release cycle. (I skimmed the README, but didn't see a formal process for this, hopefully this is sufficient.)

### CODE REVIEW

**Comment by colemickens** [comment]
(hm, it appears I broke my CLA when transitioning to Red Hat, let me get this addressed...)

**Comment by idvoretskyi** [comment]
Please, note https://github.com/kubernetes/sig-release/pull/106.

Since Tim already has experience in the release process as a shadow for 1.10 bug triaging, I would suggest you, Cole, to apply as a shadow for 1.11.

That's a great opportunity for being a role lead in 1.12 or later.

**Comment by colemickens** [comment]
CLA bot is happy, and I've updated to be the shadow bug triage for v1.11. Thanks!

**Comment by idvoretskyi** [comment]
PTAL @tpepper

**Comment by idvoretskyi** [comment]
@jberkus

**Comment by tpepper** [comment]
We just chatted and yep...

/lgtm
/approve

**Pull request merged**
