### PR TITLE
Update release notes draft to version v1.20.0-alpha.2

### PR DESCRIPTION
**Pull request by wilsonehusin**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.20.0-alpha.2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

### CODE REVIEW

**Comment by wilsonehusin** [comment]
I think I might have made a mistake on running the command for this PR
```
krel release-notes --create-draft-pr --repo ~/workspace/go/src/k8s.io/kubernetes --fork wilsonehusin/sig-release
```
I didn't use `--fix` because I thought I could use it later to see a clear difference on what's generated and what I edited, but now rerunning with `--fix` says that branch on my fork already exist.

1. I'm thinking the only way I can fix this is to close this PR and delete the existing branch, then redo with `--fix`?
1. I also noticed the diff here seems to be from v1.19.0 when alpha.1 was from v1.19.0-rc1, is this expected?

cc: @JamesLaverack @puerco

**Comment by wilsonehusin** [comment]
oops I probably should've mentioned other release notes team as well

cc: @celestehorgan @tanjacky @soniasingla

**Comment by celestehorgan** [comment]
1. Yes, if you close this PR and redo with `--fix` that will work 👍 

As for #2, i'll wait for someone else to respond!

**Comment by JamesLaverack** [comment]
Hrm. The base (using 1.19.0 vs 1.19.0-rc.1) is strange. But I know there was some 'unusual' branching behaviour around the 1.19 release. @puerco what's your take?

**Comment by wilsonehusin** [comment]
Closing this -- will redo another one!

**Comment by puerco** [comment]
Hey, yes this was in fact the branching change that happened for 1.19. From now on we start generating the release notes including commits after the release is cut (from v1.19.0). Previously we considered commits from the first rc (v1.19.0-rc.1) because the branch was created then.

**Comment by puerco** [comment]
In the case of this PR @wilsonehusin it was easier to close and re-run, after all it only contained the auto generated draft. But keep in mind that you can submit any number of updates to the draft, in fact I'd encourage you to review a couple of PRs, submit and repeat.

**Pull request closed without merging**
