### PR TITLE
Final final draft of release notes (for real this time)

### PR DESCRIPTION
**Pull request by onyiny-ang**
Some nits were discovered in the release notes and since the release is delayed, there is an opportunity to correct any other minor issues. Please comment on the PR if there are any:
-  minor spelling/grammatical errors we may have missed
-  non-user facing notes that could be removed to further reduce the size of the notes

I will squash any further commits and remove the hold tomorrow before the release is built.

/hold
/assign @claurence 
/cc @tpepper @jeefy @saschagrunert @nickchase

### CODE REVIEW

**Comment by tpepper** [comment]
NOTE: the hold should only be lifted by @onyiny-ang when ready.  We're liable to have a few other things trickle in with the release blocked currently.

**Comment by onyiny-ang** [comment]
Relocated another note to a more appropriate place. Double checked that no new notes came in 5 minutes ago, I think this should be good to go but will wait to remove the hold until closer to the release meeting.

**Comment by tpepper** [comment]
Still
/lgtm
and trying to keep it close to merge ready although if/when amended tomorrow it will need it again.

**Comment by onyiny-ang** [comment]
/hold cancel
:tada:

**Pull request merged**
