### PR TITLE
Added 1.18 logo

### PR DESCRIPTION
**Pull request by alejandrox1**
Signed-off-by: alejandrox1 <alarcj137@gmail.com>

/cc @justaugustus @tpepper @onlydole @mrbobbytables ptal :heart:

### CODE REVIEW

**Comment by onlydole** [comment]
Delightful! :smile:

/lgtm

**Comment by alejandrox1** [comment]
xref: https://github.com/alejandrox1/sig-release/tree/1.18-logo/releases/release-1.18

**Comment by alejandrox1** [comment]
wait
/hold
lol
name

**Comment by alejandrox1** [comment]
lol
/hold cancel

**Comment by onlydole** [comment]
/lgtm 
🎉 🎉 🎉

**Pull request merged**
