### PR TITLE
patches: update schedule for the next patches releases

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Update patches releases schedule

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

/cc @tpepper

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/hold
for more @kubernetes/sig-release-leads approvals

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
