### PR TITLE
Updated slack handle

### PR DESCRIPTION
**Pull request by josiahbjorgaard**
Slack handle for Josiah Bjorgaard is changed from Josiah Bjorgaard to jb

### CODE REVIEW

**Comment by jeefy** [comment]
Derp, approved without noticing the invalid commit message. 

@josiahbjorgaard Please edit your commit message to not include any @ symbols. Thanks!

/lgtm cancel

**Comment by josiahbjorgaard** [comment]
@jeefy I fixed the commit message

**Pull request merged**
