### PR TITLE
Update SECURITY_CONTACTS

### PR DESCRIPTION
**Pull request by hasheddan**
#### What type of PR is this:

/kind cleanup

#### What this PR does / why we need it:

Adds @hasheddan @jeremyrickard  and removes @tpepper from `SECURITY_CONTACTS`.

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/sig-release/issues/1322 https://github.com/kubernetes/sig-release/issues/1321

#### Special notes for your reviewer:

/hold
/assign @justaugustus @saschagrunert

### CODE REVIEW

**Review by markyjackson-taulia — COMMENTED** [review]
/lgtm

**Review by onlydole — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by justaugustus — CHANGES_REQUESTED** [review]
Add @jeremyrickard in, as he'll be confirmed as TL by EOD tomorrow.
ref: https://groups.google.com/g/kubernetes-dev/c/78E3IobBKH0

**Comment by hasheddan** [comment]
@justaugustus done :+1:

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Awesome, thanks @hasheddan!
/lgtm
/approve
/hold cancel

**Pull request merged**
