### PR TITLE
CHANGELOG: add hyperlinks for 'kubectl debug' description

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this:
/kind cleanup

#### Which issue(s) this PR fixes:
None

### CODE REVIEW

**Comment by palnabarun** [comment]
/retitle CHANGELOG: add hyperlinks for 'kubectl debug' description

/assign @wilsonehusin

**Comment by wilsonehusin** [comment]
@chymy, I noticed that you have a plenty of PRs for fixes in the release notes. I'm happy to go through our policy so we can make sure your work is incorporated in the result with higher success rate for them being merged. Can we set up a time to discuss?

The short version:
- Please take another look at [trivial edits policy](https://github.com/kubernetes/community/blob/dae5fc7d519cf72f18c3a915e8c4b80051440576/contributors/guide/pull-requests.md#trivial-edits).
- **Pre-release changes need to happen in k/sig-release, not k/k** -- as the time of this writing, pre-release is 1.21
- Changes for versions prior to pre-release can go directly to k/k since they're not getting regenerated.
- Changes for [EOL versions](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history) should not be made at all, I don't think it's a good idea to encourage activity on EOL releases.

I'm not particularly inclined to merge this change to k/k or k/sig-release as it seem to fall under trivial edits ([as I have stated in your k/k PR](https://github.com/kubernetes/kubernetes/pull/98652#issuecomment-770676932)) -- I'd be more than happy to advocate for the changes **if**:
- functional errors and broken links to PR / issues / documentation
  - username changes isn't as valuable, since they can still be traced through the PR or issues
- readability issues (improper formatting for a section, etc)
- even better if they are all in the same batch, as it helps us review.

Is that helpful?

**Comment by chymy** [comment]
> @chymy, I noticed that you have a plenty of PRs for fixes in the release notes. I'm happy to go through our policy so we can make sure your work is incorporated in the result with higher success rate for them being merged. Can we set up a time to discuss?
> 
> The short version:
> 
> * Please take another look at [trivial edits policy](https://github.com/kubernetes/community/blob/dae5fc7d519cf72f18c3a915e8c4b80051440576/contributors/guide/pull-requests.md#trivial-edits).
> * **Pre-release changes need to happen in k/sig-release, not k/k** -- as the time of this writing, pre-release is 1.21
> * Changes for versions prior to pre-release can go directly to k/k since they're not getting regenerated.
> * Changes for [EOL versions](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history) should not be made at all, I don't think it's a good idea to encourage activity on EOL releases.
> 
> I'm not particularly inclined to merge this change to k/k or k/sig-release as it seem to fall under trivial edits ([as I have stated in your k/k PR](https://github.com/kubernetes/kubernetes/pull/98652#issuecomment-770676932)) -- I'd be more than happy to advocate for the changes **if**:
> 
> * functional errors and broken links to PR / issues / documentation
>   
>   * username changes isn't as valuable, since they can still be traced through the PR or issues
> * readability issues (improper formatting for a section, etc)
> * even better if they are all in the same batch, as it helps us review.
> 
> Is that helpful?

Thank you very much @wilsonehusin . Get it.

**Pull request closed without merging**
