### PR TITLE
Add code freeze exception requests for v1.30 

### PR DESCRIPTION
**Pull request by salehsedghpour**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

This PR updates the `exceptions.yaml` file listing the KEPs which had submitted exception requests post code freeze for the v1.30 release.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

/assign @katcosgrove @gracenng @neoaggelos @ramrodo @sanchita-07 @fsmunoz

### CODE REVIEW

**Review by sanchita-07 — COMMENTED** [review]
Are we yet to include the exception requests that were denied?

**Comment by salehsedghpour** [comment]
> Are we yet to include the exception requests that were denied?

I didn't see any denied exception requests for the code freeze.

**Review by saschagrunert — APPROVED** [review]

**Comment by sanchita-07** [comment]
> > Are we yet to include the exception requests that were denied?
> 
> I didn't see any denied exception requests for the code freeze.

I think KEP - [2400](https://github.com/kubernetes/enhancements/issues/2400) exception request was cancelled.
Slack Discussion Thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1709665367366409?thread_ts=1709665367.366409&cid=C2C40FMNF

**Comment by salehsedghpour** [comment]
Yes, it was withdrawn by the enhancement owner. And as I talked to @katcosgrove, we couldn't find such status. we've searched through the past few releases.

**Pull request merged**
