### PR TITLE
Kubernetes 1.21 Major Themes

### PR DESCRIPTION
**Pull request by wilsonehusin**
x-ref: https://github.com/kubernetes/sig-release/discussions/1436

Signed-off-by: Wilson E. Husin <whusin@vmware.com>

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Working space to compile major themes.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

/cc ashnehete melodychn pmmalinov01 soniasingla

### CODE REVIEW

**Comment by soniasingla** [comment]
@wilsonehusin I noticed as per the conversation on our slack group that @pmmalinov01 and you also had written some of the entries already, do you mind pushing the content into draft PR so that the others know what to pick up quickly? Also, we can edit it later on :)

**Comment by wilsonehusin** [comment]
Added! Status is recent now

**Comment by wilsonehusin** [comment]
Preview of [rendered Markdown is here](https://github.com/wilsonehusin/sig-release/blob/1.21-major-themes/releases/release-1.21/release-notes/major-themes.md).

**Pull request merged**
