### PR TITLE
Update release notes draft to version v1.22.0-alpha.2

### PR DESCRIPTION
**Pull request by Damans227**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.22.0-alpha.2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

### CODE REVIEW

**Comment by pmmalinov01** [comment]
Great work @Damans227. I will put it on hold just to allow the rest of the team to review it in the upcoming days.
/hold

**Comment by Damans227** [comment]
> Great work @Damans227. I will put it on hold just to allow the rest of the team to review it in the upcoming days.
> /hold

Ok, thanks for doing that @pmmalinov01 Appreciate it!

**Comment by pmmalinov01** [comment]
@Damans227 have you used `--fix` in the krel rel-notes command? I am asking because in this pull request we there are missing files.
- sessions
- map files

Also, it tries to overwrite already changed release notes items. If you have used `--fix`, we need to investigate why we have this effect. Check your history to see if this is the case, if that is yes you will have to rerun the krel work flow and cancel the PR and delete the branch at your fork. 
If you have any problems please do not hesitate to reach out.

**Comment by Damans227** [comment]
Good catch @pmmalinov01 I checked the terminal history, and the --fix tag wasn't used. This is the command I ran:

**Comment by puerco** [comment]
@pmmalinov01 do you recognizr the changes being reverted to be the modifications defined in the maps? If so, they should be taken into account. Even if you don't set `--fix`.

**Comment by puerco** [comment]
I just checked and they are. This is a bug. Most likely `krel` is not pulling down the maps when running without --fix.  I'll try to take a look this afternoon after work. Sorry about that :)

**Comment by Damans227** [comment]
> @pmmalinov01 do you recognizr the changes being reverted to be the modifications defined in the maps? If so, they should be taken into account. Even if you don't set `--fix`.



> I just checked and they are. This is a bug. Most likely `krel` is not pulling down the maps when running without --fix. I'll try to take a look this afternoon after work. Sorry about that :)

I see.. should I now go ahead and run the command again with the `--fix `tag ?

**Comment by pmmalinov01** [comment]
@puerco Can we do the following, create an issue that describes the bug, and I will try to smooth it out with your guide in the next couple of days? 

@Damans227 Yes you have to rerun it. But first, clear the branch at your fork(you krel will fail because it already has the same branch name). I had an issue running krel without `$EDITOR` in my environment. So you may want to set the variable to something that suits you. Also, we will have to close this PR.

**Pull request closed without merging**
