### PR TITLE
Add SIG Chair / Technical Lead onboarding requirements

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:
This adds all necessary permissions to a new technical-leads.md
document.
#### Which issue(s) this PR fixes:
None
#### Special notes for your reviewer:
None

### CODE REVIEW

**Comment by saschagrunert** [comment]
> * Move this to `leads/onboarding.md`. We'll generally share the same permissions between Chairs and Technical Leads, so let's let the document generally cover both.

Done :heavy_check_mark: 

> * Let's create a GH issue template for this, like we have for Release Managers. This doc should speak to responsibilities, while the issue template will be actionable and auditable for assigning permissions.

Done :heavy_check_mark: 

> * Review the [SIG/WG Lifecycle doc](https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md) and the k/community [Chairs & Tech Leads section](https://github.com/kubernetes/community/tree/master/contributors/chairs-and-techleads) for hints on things that should be added here. For example, you'll need access to Zoom, as well as getting added to the SECURITY_CONTACTS for our repos.

In progress… :hourglass_flowing_sand: 

> * You and @alejandrox1 should start PR-ing yourselves into various places. Your permissions should match @tpepper and mine.

In progress… :hourglass_flowing_sand:

**Comment by saschagrunert** [comment]
I think most of the parts are covered and reflected in the document. PTAL @kubernetes/sig-release-admins

**Comment by saschagrunert** [comment]
Found one more: https://github.com/kubernetes/k8s.io/pull/1050

**Comment by justaugustus** [comment]
Did more cleanup here: https://github.com/kubernetes/k8s.io/pull/1080
...which require some doc updates, but let's iterate.

/lgtm
/approve

**Pull request merged**
