### PR TITLE
Clarify that release notes team members should join k-sigs

### PR DESCRIPTION
**Pull request by JamesLaverack**
Also remove release notes as an example of a team that does not need org membership right away, as you do.

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Release notes team members (within the release team) generally open pull requests to both [kubernetes/release](https://github.com/kubernetes/sig-release) and [kubernetes-sigs/release-notes](https://github.com/kubernetes-sigs/release-notes) as part of their duties. Becoming members of both organisations streamlines reviews for these changes.

#### Which issue(s) this PR fixes:

None.

#### Special notes for your reviewer:

None.

### CODE REVIEW

**Comment by puerco** [comment]
/lgtm 
I'd only add a note (esp for new shadows) on how to request k-sigs membership, but we can add that once we lay how the next team will work and start documenting it.

**Comment by saschagrunert** [comment]
/hold 
for @puerco's comment

**Comment by JamesLaverack** [comment]
@puerco I've updated with a link to the documentation (after someone in `#sig-contribex` on Slack [helpfully linked me!](https://kubernetes.slack.com/archives/C1TU9EB9S/p1596635764086600?thread_ts=1596635425.086500&cid=C1TU9EB9S))

**Comment by puerco** [comment]
Thanks @JamesLaverack !
I think I should follow these instructions and join kubernetes-sigs myself  :)

/lgtm

**Comment by puerco** [comment]
/hold cancel
and thanks to @xmudrii for the link !

**Pull request merged**
