### PR TITLE
Update 1.26 OWNER_ALIASES

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

#### What type of PR is this:

/kind cleanup
/priority important-soon

#### What this PR does / why we need it:

This PR updates OWNER_ALISES for the 1.26 RT

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Question: Should I remove the 1.21 Release Team?

### CODE REVIEW

**Comment by leonardpahlke** [comment]
cc @palnabarun

**Comment by leonardpahlke** [comment]
ref: release team lead onboarding issue https://github.com/kubernetes/sig-release/issues/2006

**Comment by palnabarun** [comment]
I think both 1.21 and 1.22 can be removed now since those versions have reached end of life.

**Comment by leonardpahlke** [comment]
1.21 & 1.22 RT removed

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
