### PR TITLE
Add final release notes draft

### PR DESCRIPTION
**Pull request by cartyc**
The release notes team is happy to present the final release notes draft!

Huge thanks to everyone who helped make this document come to life :) 

/assign @guineveresaenger 
/cc @bridgetkromhout @evillgenius75

### CODE REVIEW

**Comment by guineveresaenger** [comment]
WOOOOO! Awesome work, release notes team! ✨ 💖 

/approve
/hold

**Comment by cartyc** [comment]
An extra special thanks to @saschagrunert for helping review the final doc  🎉

**Comment by guineveresaenger** [comment]
/lgtm

nice work!

**Pull request merged**
