### PR TITLE
Minor comms handbook updates

### PR DESCRIPTION
**Pull request by sfotony**
Moved initial team reference from release week 3 to release week 1, remove v1.19 references

/sig release
/cc @jrsapi @jeremyrickard @hasheddan @palnabarun @savitharaghunathan
/kind cleanup
/area area/release-team
/assign @jrsapi @jeremyrickard @hasheddan @palnabarun @savitharaghunathan

### CODE REVIEW

**Review by savitharaghunathan — APPROVED** [review]
/lgtm

**Review by hasheddan — COMMENTED** [review]
@sfotony thanks for this update :) could you clean up the commits?

**Comment by savitharaghunathan** [comment]
@sfotony 👋 Thanks for this PR. Can you fix the Invalid commit messages, please?

**Pull request merged**
