### PR TITLE
Add Release Team Diagram

### PR DESCRIPTION
**Pull request by JamesLaverack**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Adds an SVG diagram that shows the roles in the release team. This is to aid the text it sits alongside in describing the team's structure.

### CODE REVIEW

**Comment by JamesLaverack** [comment]
I realise that I didn't consider dark mode users. It looks as intended in light mode:
Screenshot 2021-04-16 at 22 12 12
but in dark mode the "fade" effect does not work and the text without a background is almost invisible:
image

**Comment by annajung** [comment]
I think we should get rid of "typically 3-4 shadows per area" since there have been talks of increasing the number of shadows and leaving it flexible for each sub Leads due to the increasing amount of enhancements past few releases. 

I think the dark mode looks okay especially if we get rid of the text then it wouldn't be a problem that it doesn't show up :)

**Comment by JamesLaverack** [comment]
> I think we should get rid of "typically 3-4 shadows per area" since there have been talks of increasing the number of shadows and leaving it flexible for each sub Leads due to the increasing amount of enhancements past few releases.

:+1: I've removed it.

I've updated it to use opacity instead of distinct 'lighter' colours anyway, so that it'll work on dark backgrounds much better.

Screenshot 2021-04-21 at 01 05 01
Screenshot 2021-04-21 at 01 05 51

**Comment by PI-Victor** [comment]
was about to suggest a gray color, but i agree with the suggestion to remove it from there.
thanks for the PR, i guess we can merge it?
/lgtm

**Comment by palnabarun** [comment]
/lgtm
/approve

Thanks @JamesLaverack 🎉

**Pull request merged**
