### PR TITLE
Update release notes draft to version v1.23.0-alpha.3

### PR DESCRIPTION
**Pull request by parul5sahoo**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.23.0-alpha.3

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

### CODE REVIEW

**Comment by cici37** [comment]
Is there only one commit has release notes for the current release cut? It does not sound right to me. Let me double check

**Comment by parul5sahoo** [comment]
No this is a test PR. Can you check if the PR is okay?
I will close this and create another PR with all the commits.

**Comment by cici37** [comment]
The pr sounds great if it has all the changes in ^^. Please close this one and go ahead to create the actual PR. :)

**Comment by cici37** [comment]
btw when you edit the yaml file, we only need the first three fields in. e.g.:
```
pr: 104483
releasenote:
  text: client-go impersonation config can specify a UID to pass impersonated uid
    information through in requests.
```
You could refer to the previous files under `releases/release-1.23/release-notes/maps/`

**Pull request closed without merging**
