### PR TITLE
Update release notes handbook with krel information 

### PR DESCRIPTION
**Pull request by puerco**
/kind documentation

#### What this PR does / why we need it:
This PR updates the docs for generating the kubernetes release notes using the latest procedure which uses krel. This is based on the documentation written by @reylejano-rxm and updated to the latest krel version.

#### Which issue(s) this PR fixes:
The current documentation is still based on the old release notes tool, this PR updates the instructions for the release notes team in order to generate the notes using the latest tool set.

#### Special notes for your reviewer:
/cc @reylejano-rxm

### CODE REVIEW

**Comment by puerco** [comment]
@justaugustus would you prefer to strip all usage specific docs from the handbook and have it all only in the krel docs? It seems to me more logical and easier to maintain.

Also: who can I talk to regarding the old release-notes tool? @saschagrunert maybe ?

**Comment by reylejano-rxm** [comment]
@puerco Documentation looks great. 
I'll wait on how you want to proceed with this PR after the comment to have Documentation closer to the code.

**Comment by justaugustus** [comment]
> @justaugustus would you prefer to strip all usage specific docs from the handbook and have it all only in the krel docs? It seems to me more logical and easier to maintain.

@puerco -- Yes please! https://github.com/kubernetes/sig-release/pull/1028 is a good example.

> Also: who can I talk to regarding the old release-notes tool? @saschagrunert maybe ?

Yep. Sascha is a great person to chat with about it.

**Comment by justaugustus** [comment]
Any update on this one?

**Comment by puerco** [comment]
@justaugustus I've removed the krel technical information and did a major update to the role handbook with two major themes:

1. Updated the release notes generation process instructions to mention krel instead of the old tool, avoiding any details in order to avoid maintaining a second set of instructions and replaced them with links to the krel docs.
2. Tried to adjust the handbook milestones to match the new longer release cycle.

/cc @onlydole

**Comment by reylejano-rxm** [comment]
@puerco , on the release day portion, do you think the steps that you or the last release notes lead did on 1.18 release day should be added like deleting the pre-release release-notes drafts in md and removing the pre-release versions from the assets.ts array?

**Comment by puerco** [comment]
I've been thinking that removing the prerelease json files and cleaning the assets will be part of the final automation and will not happen this release (by hand). On th other hand, the .md drafts are preserved in the repo (eg [v1.15](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.15/release-notes-draft.md) ).

But I'm sure I might be missing other release day tasks, can you think of any ?

**Comment by reylejano-rxm** [comment]
> But I'm sure I might be missing other release day tasks, can you think of any ?

@ puerco, can't think of anything else

/lgtm

**Comment by onlydole** [comment]
@puerco and @justaugustus - If this looks good to both of you, I think this is good to merge in.

**Comment by puerco** [comment]
It's currently valid. Probably it won't be any more for 1.19-beta.0 but we'll keep updating it as we go :writing_hand:

**Pull request merged**
