### PR TITLE
Add the release theme for the release cycle v1.26 

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Add the release theme for 1.26

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

/assign @palnabarun

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/hold

for approval from @palnabarun

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

/honk

**Comment by adammw** [comment]
@leonardpahlke are you the creator of this release logo? I'm loving the art style and wondering if other versions (such as a wallpaper size) could be released...

**Comment by leonardpahlke** [comment]
Hey, that's not planned at the moment.

**Comment by leonardpahlke** [comment]
but I like the idea :)

**Comment by leonardpahlke** [comment]
@adammw you are in luck we now have a wallpaper of the logo see https://github.com/kubernetes/sig-release/tree/master/releases/release-1.26#kubernetes-126-electrifying (there is also an extra dope animated version 😉 )

**Pull request merged**
