### PR TITLE
update ci signal shadow list and project board ref

### PR DESCRIPTION
**Pull request by leonardpahlke**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Document 1.24 ci signal shadows and update of used ci signal tools for release cycle
@voigt, @lauralorenz, @shuheiktgw and @nivedita-coder 

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

The [old ci signal project board](https://github.com/orgs/kubernetes/projects/11) is no longer used. The [new project board](https://github.com/orgs/kubernetes/projects/68) replaces the old board & the excel tracking sheet. See [slack discussion](https://kubernetes.slack.com/archives/CN0K3TE2C/p1639768897186400).

### CODE REVIEW

**Review by JamesLaverack — APPROVED** [review]
/approve

**Comment by JamesLaverack** [comment]
Oh I tried to merge it, but you need to fully rebase it. 🙈

**Comment by leonardpahlke** [comment]
I will do it later don't worry

**Review by JamesLaverack — APPROVED** [review]
/lgtm

**Pull request merged**
