### PR TITLE
Integrate 1.21 major themes to release notes draft

### PR DESCRIPTION
**Pull request by wilsonehusin**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

To complete release notes for Kubernetes 1.21

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

We should only merge this once we know **for sure** that we're releasing in 24 hours (just in case there are updates to release notes).

/hold

/cc ashnehete melodychn pmmalinov puerco soniasingla

### CODE REVIEW

**Comment by wilsonehusin** [comment]
oops missing some people

/cc pmmalinov01

for visibility

/cc palnabarun kikisdeliveryservice savitharaghunathan bai

**Review by soniasingla — APPROVED** [review]
/lgtm

**Comment by wilsonehusin** [comment]
past mid-day for Tuesday in Pacific time, I'm going to let this go 😄 

/hold cancel

**Comment by puerco** [comment]
:tada: 
/pony

**Pull request merged**
