### PR TITLE
Remove reverted PRs from release notes

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

These PRs were reverted and shouldn't be in release notes: https://github.com/kubernetes/kubernetes/pull/129172.
https://kubernetes.slack.com/archives/C2C40FMNF/p1733991200800589

#### Which issue(s) this PR fixes:

Issue #2695 (Not `Fixes`)

### CODE REVIEW

**Comment by Vyom-Yadav** [comment]
/assign @satyampsoni @npolshakova 

Do we need to remove these entries from any place else? I'm assuming [relnotes.k8s.io](https://relnotes.k8s.io/) would automatically pick this up i.e. sig-release/release-notes is the data source.

**Comment by satyampsoni** [comment]
Thanks for the PR @Vyom-Yadav 
According to this diagram, relnotes.k8s.io will automatically take the changes. 
https://github.com/kubernetes/sig-release/blob/master/release-engineering/img/kubernetes-release-notes.svg

**Comment by Vyom-Yadav** [comment]
Thanks @satyampsoni , if this is fine, can you lgtm and merge?

**Pull request merged**
