### PR TITLE
Schedule 1.22 Retrospective

### PR DESCRIPTION
**Pull request by guineveresaenger**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Schedules a release retrospective for Kubernetes 1.22

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

/cc @savitharaghunathan 
/cc @kubernetes/sig-release-leads

### CODE REVIEW

**Comment by guineveresaenger** [comment]
For scheduling review:

/hold
/sig-contributor-experience

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by guineveresaenger** [comment]
Via [Slack discussion](https://kubernetes.slack.com/archives/C1TU9EB9S/p1625680041313400) I'm going to unhold this.

Thanks everyone!

/hold cancel

**Pull request merged**
