### PR TITLE
Update various urls across sig-release documentation

### PR DESCRIPTION
**Pull request by bharitwal**
Review documentation as a new shadow and update as required.

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Reviewed existing documentation as a new shadow and updated where required. 

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

/cc @leonardpahlke @palnabarun

### CODE REVIEW

**Review by leonardpahlke — APPROVED** [review]
lgtm
Thank you

**Comment by leonardpahlke** [comment]
I just noticed stephen and nabarun are both OOO, sry

/assign @puerco

**Comment by puerco** [comment]
Thank you @bharitwal !
/approve

**Pull request merged**
