### PR TITLE
Add exceptions.yaml for 1.22

### PR DESCRIPTION
**Pull request by JamesLaverack**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Add `exceptions.yaml` file for the Kubernetes 1.22 release, as described in the [enhancements documentation](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md#enhancement-lead).

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
wow too fast :/

**Comment by JamesLaverack** [comment]
😅 Wpuld you like me to back it out @cpanato?

**Comment by cpanato** [comment]
no no, i think that is fine :) if need anything else we can followup on that

**Pull request merged**
