### PR TITLE
Update patch release schedule for 2020-03

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind cleanup
> /kind design
> /kind documentation
> /kind feature

/kind documentation

**What this PR does / why we need it**:
Update patch release schedule for 2020-03
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by feiskyer** [comment]
@justaugustus Updated the suggested days, PTAL

**Comment by justaugustus** [comment]
Thanks @feiskyer! Thanks Tim for reviewing as well!
/lgtm
/approve
/hold cancel

**Pull request merged**
