### PR TITLE
Release Notes draft for k/k v1.18.0-beta.0

### PR DESCRIPTION
**Pull request by puerco**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

This is the first version of the release notes draft generated with krel. Please take a look and let us know if everything seems in order. We are testing the new release-notes subcommand and ironing out some issues we found. But in the meanwhile here is the first draft!

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

This version of the draft was generated using this invocation of krel:
```
krel release-notes --create-draft-pr --draft-org=puerco --tag v1.18.0-beta.0
```

cc/ @saschagrunert @evillgenius75 @JamesLaverack

### CODE REVIEW

**Comment by puerco** [comment]
OK, first issue. The PR went out using the nobody@k8s which is hardcoded here:
https://github.com/kubernetes/release/blob/77f04ec7dea6f7ec581811855250928d74939b3b/pkg/git/git.go#L718-L720

**Comment by puerco** [comment]
Because of the hardcoded email, the PR failed the CLA test. 

We are debating how to get the user email. We are assuming that since the local git auth stuff has been removed from git.go we cannot rely on the local user credentials. Should we require a flag like `--user-email`? Maybe query the github api and try to guess the user's email from te token ?

**Comment by justaugustus** [comment]
@puerco -- Can you adjust the commit author to you using

```shell
git commit --amend --author="First Last Name <email-address>" --signoff
```

/lgtm cancel
/hold

**Comment by puerco** [comment]
Done @justaugustus !

**Comment by justaugustus** [comment]
Thanks!
/lgtm
/approve
/hold cancel

**Pull request merged**
