### PR TITLE
Update release notes draft to version v1.19.0-beta.2

### PR DESCRIPTION
**Pull request by wilsonehusin**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.19.0-beta.2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`
```
krel release-notes --create-draft-pr --org wilsonehusin
```

This is the first release notes generated after the refactor on `krel` (kubernetes/release#1350)

cc: @puerco @reylejano-rxm @JamesLaverack @AGMETEOR

### CODE REVIEW

**Comment by puerco** [comment]
I looks fine to me, I think we can now say that the release notes process is now fully automated :partying_face: 
/lgtm

**Comment by onlydole** [comment]
Thank you, everyone! This looks great! 
/lgtm
/approve

**Pull request merged**
