### PR TITLE
Update Timeline and Responsibilities for Enhancement Lead Handbook

### PR DESCRIPTION
**Pull request by kacole2**
Updated the Milestone Activities + Timing section to put the timing and responsiblity associated needed for the role.

Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
Thank you SOOOOOOOO much for getting this updated, Kenny!
I'll review when I have a chance. Putting an explicit hold on it until I do.

/hold

**Comment by justaugustus** [comment]
Great work, @kacole2!

/hold cancel
/lgtm
/approve

**Comment by idvoretskyi** [comment]
Great one, @kacole2. Thanks!

**Pull request merged**
