### PR TITLE
Linked enhancements tracking board in release readme

### PR DESCRIPTION
**Pull request by sreeram-venkitesh**
#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Links the enhancement tracking board for v1.31 release to the v1.31 release's readme file.

#### Which issue(s) this PR fixes:

None.

#### Special notes for your reviewer:

CC: @neoaggelos

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by sreeram-venkitesh** [comment]
I need to update the link to the feature blog tracking board before merging this PR.

**Comment by saschagrunert** [comment]
@sreeram-venkitesh this PR got already merged, you have to revert those changes to go back to the original state.

**Comment by sreeram-venkitesh** [comment]
Ah I didn't notice when looking at it from my phone. I can raise another PR for adding the link, it doesn't need to be done in the same PR.

**Pull request merged**
