### PR TITLE
Improve release cut documentation and issue template

### PR DESCRIPTION
**Pull request by palnabarun**
#### What type of PR is this:

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

Some general improvements to the release cut issue template.

#### Which issue(s) this PR fixes:

Partially fixes https://github.com/kubernetes/sig-release/issues/1734

#### Special notes for your reviewer:

None

/cc @kubernetes/release-managers
/priority important-soon
/area release-eng

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you for the update @palnabarun!

**Comment by palnabarun** [comment]
Thank you @saschagrunert for reviewing the changes! I've made a few more improvements. Can you please have a look and re-LGTM?

**Comment by palnabarun** [comment]
/hold cancel
(all changes I plan to land are in the PR)

**Pull request merged**
