### PR TITLE
Delete tombstone files in sig-release/security

### PR DESCRIPTION
**Pull request by tddorgtfo**
For kubernetes/community#3220

### CODE REVIEW

**Comment by tddorgtfo** [comment]
fixes: #3220

**Comment by nikhita** [comment]
I think the entire directory can be removed.

/uncc @cblecker @parispittman @eduartua 
/assign @justaugustus

**Comment by justaugustus** [comment]
@tddorgtfo -- Thanks for this! As @nikhita mentioned, we can remove the entire directory as security documentation has moved to https://git.k8s.io/security.

**Comment by nikhita** [comment]
@tddorgtfo Looks good! Can you also squash the commits into a single commit?

**Comment by justaugustus** [comment]
Thanks @tddorgtfo!
/lgtm
/approve

**Pull request merged**
