### PR TITLE
Add OWNERS file for release-signal handbook

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
#### What type of PR is this:

/kind cleanup

#### What this PR does / why we need it:

The Release Signal team was introduced in v1.30. The OWNERS file was missing from the release signal handbook. We may also remove the ci signal and the bug triage handbook in the upcoming cycles.

#### Which issue(s) this PR fixes:

None

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
