### PR TITLE
[WIP] Update docs handbook

### PR DESCRIPTION
**Pull request by tfogo**
Follow up from #139.

/cc @zparnold 

Zach, do you have write access to this branch?

### CODE REVIEW

**Comment by justaugustus** [comment]
@tfogo can we clean up the conflicts on this?

**Comment by justaugustus** [comment]
What's the status of this?
Can we clean up the conflicts and also [make sure the docs handbook link matches the structure of the other roles i.e., `release-team/role-handbooks/docs/README.md`](https://github.com/kubernetes/sig-release/pull/409#discussion_r241938228)

**Comment by justaugustus** [comment]
/assign @jimangel 

Jim -- can you pick up this branch and carry the Docs handbook forward?

**Comment by justaugustus** [comment]
@jimangel -- bump on this one.

**Comment by jimangel** [comment]
@justaugustus I have a living hackmd.io doc that I and the shadows are working off of to edit / improve. I was planning on PR'ing at the end of the cycle. Would you rather we work on it publicly as a PR?

**Comment by justaugustus** [comment]
@jimangel -- yep. This has been lingering for a few cycles, so I'd prefer some iterations in the open.

**Comment by jimangel** [comment]
> @jimangel -- yep. This has been lingering for a few cycles, so I'd prefer some iterations in the open.

All good! I'll have something up this weekend. Thanks!

**Comment by justaugustus** [comment]
Much appreciated... but don't work on the weekend, if you don't need to! :hugs:

**Comment by tfogo** [comment]
@jimangel will be opening a new PR for this

**Pull request closed without merging**
