### PR TITLE
Add 1.21 Bug Triage shadows to the release team

### PR DESCRIPTION
**Pull request by erismaster**
#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:
Add 1.21 Bug Triage Shadows to the release team page
#### Special notes for your reviewer:
/assign @palnabarun @onlydole @kikisdeliveryservice @savitharaghunathan @bai

### CODE REVIEW

**Comment by bai** [comment]
Welcome to the team! 🎉

**Review by onlydole — APPROVED** [review]
Thank you, @erismaster! 

/lgtm

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Pull request merged**
