### PR TITLE
release-1.24: push back rc.0 release date

### PR DESCRIPTION
**Pull request by palnabarun**
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Pushes back Kubernetes v1.24.0-rc.0 release date

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

### CODE REVIEW

**Comment by ameukam** [comment]
cc @saschagrunert @haircommander

**Comment by palnabarun** [comment]
/hold cancel
the date is updated

**Pull request merged**
