### PR TITLE
Correct grammatical error

### PR DESCRIPTION
**Pull request by Damans227**
#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:

Corrects a grammatical error in the release notes handbook.

#### Which issue(s) this PR fixes:
N/A

### CODE REVIEW

**Comment by Damans227** [comment]
> @Damans227: you cannot LGTM your own PR.

Lol!! Thanks Prow ;)

**Review by cpanato — COMMENTED** [review]
thanks
/approve
/lgtm

**Pull request merged**
