### PR TITLE
1.19: Update release cycle timelines (pre-KubeCon release)

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this:

/kind cleanup documentation

#### What this PR does / why we need it:

This is an alternative pre-KubeCon release schedule (compared to https://github.com/kubernetes/sig-release/pull/1058).

- Move Enhancements Freeze to week 6 (was week 4)
- Move Code Freeze to week 11 (was week 9)
  
  **Deviation from SIG Release meeting:**
  We give an extra week in the dev cycle to shorten Code Freeze to 6 weeks.
  Several comments on the previous proposal said that Code Freeze was too long.

- RCs get released on a biweekly cadence (week 11, 13, 15)
- Move Cherry Pick Deadline to week 16 (was week 11)
- Move 1.19.0 release date to week 17 (was week 12)

  _This is the week before KubeCon._

- Move retro to week 19 (was week 12)

  _This is the week after KubeCon._

- Push Docs deadlines
- Add a Test Freeze milestone to coincide with Cherry Pick deadline

  From @spiffxp [on previous review](https://github.com/kubernetes/sig-release/pull/1058#issuecomment-617426898):
  "Specific request from SIG Arch conformance: typically code freeze is
  the date by which no new conformance tests are accepted, so as not to
  disrupt CI Signal and force them to chase the stability of a moving
  target. Can we get a test freeze date later in the cycle, to allow
  addition of new tests beforehand, but force fixing/reverting tests
  afterward for CI Signal stability?"

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @tpepper @onlydole 
cc: @kubernetes/release-team-leads @kubernetes/release-team 

#### Special notes for your reviewer:

**Lazy consensus timeout set for Friday, April 24, 5pm US ET.**
/hold

**Week comparison across release cycles:**

|  | 1.16 | 1.17 | 1.18 | 1.19 (current) | 1.19 (revised - pre-KubeCon) |
|---|---|---|---|---|---|
| Release Start | 1 | 1 | 1 | 1 | 1 |
| Enhancements Freeze | 5 | 4 | 4 | 4 | 6 |
| Code Freeze | 9 | 8 | 9 | 9 | 11 |
| Docs Complete | 11 | 9 | 11 | 11 | 13 |
| Cherry Pick Deadline | 11 | 11 | 11 | 11 | 16 |
| Release | 12 | 12 | 12 | 12 | 17 |
| Retrospective | 12 | 12 | 12 | 12 | 19 |

### CODE REVIEW

**Comment by onlydole** [comment]
image

/lgtm

**Comment by markyjackson-taulia** [comment]
Love it!
image

**Comment by justaugustus** [comment]
Email sent to k-dev & k-sig-leads: https://groups.google.com/d/msg/kubernetes-dev/IVpiIOZ4WcM/I_LGDpNkAgAJ

Lazy consensus timeout remains the same: **Friday, April 24, 5pm US ET**

cc-ing previous reviewers:
@liggitt @enj @johnbelamaric @dims @spiffxp @lavalamp @jberkus

**Comment by johnbelamaric** [comment]
I am OK with this.

/lgtm

**Comment by lavalamp** [comment]
I still think 6 weeks of code freeze is extreme, but it is better than 11, and I guess I'll take what I can get...

**Comment by justaugustus** [comment]
Hearing no objections to this updated proposal and having hit the lazy consensus timeout, I think we're good to merge here.

Thanks everyone for the feedback!
/hold cancel

**Pull request merged**
