### PR TITLE
[1.28] Add OWNER_ALIAS and update in alphabetical order

### PR DESCRIPTION
**Pull request by gracenng**
Fix some typos and add @gracenng in OWNER_ALIAS

/kind documentation

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks
/lgtm

**Review by leonardpahlke — APPROVED** [review]
LGTM

**Review by furkatgofurov7 — COMMENTED** [review]
Looks good, although the commit which includes `@` needs to be fixed in order to remove the auto-applied hold label

**Review by leonardpahlke — APPROVED** [review]
/lgtm

**Pull request merged**
