### PR TITLE
updated 1.20 exceptions.yaml for code freeze

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
double checking this for now...

### CODE REVIEW

**Comment by palnabarun** [comment]
@kikisdeliveryservice -- 👋🏽, can this be merged now?

**Comment by jeremyrickard** [comment]
Shall we merge this and then follow up with any cleanup needed?

**Comment by palnabarun** [comment]
@jeremyrickard -- I am okay with doing that.

**Comment by kikisdeliveryservice** [comment]
Apologies this got lost in the shuffle

**Comment by palnabarun** [comment]
Merging this for now. Let's iterate later if any changes needed. 👍🏽 

/lgtm
/approve

**Pull request merged**
