### PR TITLE
release-1.21: update release schedule with docs deadlines

### PR DESCRIPTION
**Pull request by palnabarun**
#### What type of PR is this:

/kind documentation
/kind feature

#### What this PR does / why we need it:

Update 1.21 Release Schedule with Docs related deadlines

#### Which issue(s) this PR fixes:

None

/assign
/assign @kubernetes/release-team-leads 
/cc @bai @kikisdeliveryservice @savitharaghunathan

### CODE REVIEW

**Comment by puerco** [comment]
/lgtm 

Thanks @palnabarun !

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by savitharaghunathan — APPROVED** [review]
/lgtm

**Pull request merged**
