### PR TITLE
OWNERS updates

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this:

/kind cleanup

#### What this PR does / why we need it:

- @hasheddan is now Emeritus (https://github.com/kubernetes/sig-release/issues/1667)
- Add `emeritus_approvers` section (thank you for everything @alejandrox1 @calebamiles @hasheddan @jdumars @tpepper!)

### CODE REVIEW

**Comment by puerco** [comment]
/lgtm
/approve
Thank you so much :heart:

**Comment by justaugustus** [comment]
Kicking the bots, since self-approve and Adolfo's approve didn't stick...
/lgtm
/approve
/check-cla

**Comment by justaugustus** [comment]
> @justaugustus: you cannot LGTM your own PR.

Sassy bot.
/check-owners
???

**Comment by puerco** [comment]
mmmmh
/approve

**Comment by justaugustus** [comment]
@puerco -- I did an empty `--amend` on the last commit and pushed.
This should be `/lgtm+/approve`-able now.

**Comment by cpanato** [comment]
<3

**Pull request merged**
